### ISSUE TITLE
delete_after_merge being ignored

### ISSUE THREAD

**Issue by kevinohara80** [palantir/bulldozer#112]
I'm not sure what we're doing wrong here. The branches are being merged but the `delete_after_merge` flag is being ignored and the branches aren't being deleted. I also can't see anything in the logs that mention deletion of the branch.

Here's the project `.bulldozer.yml`

```yaml
version: 1

merge:
  whitelist:
    branches: ["develop", "master"]
  blacklist:
    labels: ["no merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  branch_method:
    develop: squash
    master: merge
  options:
    squash:
      title: "pull_request_title"
      body: "pull_request_body"
      message_delimiter: ==COMMIT_MSG==
  delete_after_merge: true

update:
  whitelist:
    branches: ["develop", "master"]
  blacklist:
    labels: ["no update"]
```
