### ISSUE TITLE
Getting 404s from bulldozer deployment

### ISSUE THREAD

**Issue by ashishb** [palantir/bulldozer#144]
My server-side config file:

```
# Source: https://github.com/palantir/bulldozer/blob/develop/config/bulldozer.example.yml

# Download bulldozer from https://bintray.com/palantir/releases/download_file?file_path=com%2Fpalantir%2Fbulldozer%2Fbulldozer%2F1.6.2%2Fbulldozer-1.6.2.tgz
# tar xvf bulldozer-1.6.2.tgz
# Copy this file bulldozer.yml into config/bulldozer.yml
# Start the server: ./bulldozer-1.6.2/bin/linux-amd64/bulldozer server

# Options for the http server
server:
  # The listen address and port
  address: "0.0.0.0"
  port: 8080

# Options for logging output
logging:
  # If true, logs are printed in human-readable form. We recommend using
  # "false" to output JSON-formatted logs in production
  text: true

  # Set a minimum logging level threshold
  # Choose from: debug, info, warn, error
  level: "debug"

# Options for the HTTP Cache
cache:
  # The maximum size of the cache (specified in human readable units)
  max_size: "50 MB"

# Options for connecting to GitHub
github:
  # The URL of the GitHub homepage
  web_url: "https://github.com"
  # The base URL for v3 (REST) API requests
  v3_api_url: "https://api.github.com"
  app:
    # The integration ID of the GitHub app
    # Source: https://github.com/settings/apps/bulldozer-deployment-for-celo
    integration_id: 37493
    # A random string used to validate webhooks. Can also be set by the
    # GITHUB_APP_WEBHOOK_SECRET environment variable.
    # webhook_secret: ""

    # The private key of the GitHub app (.pem file download from GitHub). Can
    # also be set by the GITHUB_APP_PRIVATE_KEY environment variable.
    # private_key: ""

# Options for application behavior
options:
  # The path within repositories to find the bulldozer.yml config file
  configuration_path: .bulldozer.yml
  # The name of the application. This will affect the User-Agent header
  # when making requests to Github.
  app_name: "Bulldozer"
  # An optional personal access token associated with a normal GitHub user that
  # is used to merge pull requests into protected branches with push
  # restrictions. Can also be set by the BULLDOZER_PUSH_RESTRICTION_USER_TOKEN
  # environment variable.
  # push_restriction_user_token: ""
```

I am running bulldozer server using 
```
GITHUB_APP_WEBHOOK_SECRET=<REDACTED> \
  BULLDOZER_PUSH_RESTRICTION_USER_TOKEN=<REDACTED> \
  GITHUB_APP_PRIVATE_KEY=$(cat github_app_private_key.pem) \
  ./bulldozer-1.6.2/bin/linux-amd64/bulldozer server
```

When I test it on my repo: https://github.com/ashishb/bulldozer-testing/pull/1
I see  `INF http_request elapsed=0.100437 method=POST path=/api/github/webhook rid=bl48e9rpt6pu29c8g7q0 size=19 status=404`. There are no more logs even though I am logging at the debug log level. Any suggestions on what could have gone wrong or how to go about debugging this?
