### ISSUE TITLE
From 1.9.x, body: "empty_body" is not working

### ISSUE THREAD

**Issue by tanvn** [palantir/bulldozer#192]
Today, I tried to update from 1.5.0 to 1.9.1 and found out that the setting `body : "empty_body"` is not working anymore.
Below is my yaml bulldozer setting file.
```
version: 1

merge:
  whitelist:
    labels: ["merge-me"]
  blacklist:
    labels: ["do-not-merge","wip"]
  method: squash
  options:
    squash:
      title: "pull_request_title"
      body: "empty_body"
  delete_after_merge: true

update:
  blacklist:
    labels: ["do-not-update", "wip"]
  whitelist:
    labels: ["update-me"]

```
I have tried 1.5.0 to 1.8.0 and it worked well.
From 1.9.0 when merged, the message body contains all commit messages and it ignored the  `body : "empty_body"` setting.
