### ISSUE TITLE
Match all merge triggers instead of any

### ISSUE THREAD

**Issue by philBrown** [palantir/bulldozer#225]
While configuring Bulldozer, I assumed that a PR would need to match **all** triggers before being automatically merged.

For example, I'm using Bulldozer to auto-merge PRs from [Dependabot](https://dependabot.com/) with the following config
```yaml
merge:
  trigger:
    labels: ["dependencies"]
    branches: ["main"]
    branch_patterns: ["dependabot/.*"]
```
however I noticed that Bulldozer is merging other PRs with the following message
> my-repo#129 is triggered because triggering is enabled and pull request target is a triggered branch: "main"

This PR had no labels and was not within a `dependabot/*` branch name.

Is there any way to only trigger when **all** conditions match?
