### ISSUE TITLE
[FR] Make merge method configurable: merge or squash depending on conditions

### ISSUE THREAD

**Issue by atrocities** [palantir/bulldozer#266]
Bulldozer currently takes a single 'method', which applies to all PRs regardless of the state of the source branch. 

It would be nice for Bulldozer to do a regular merge when certain conditions are satisfied, and a squash merge when these conditions are not, as specified in the `.palantir/bulldozer.yml` file. These conditions can include the number of commits on the source branch, and the presence/absence of a certain label. 

The configuration could look something like this
```
merge:
  method: squash
  conditional-methods:
    merge:
      labels: ["auto-push", "generated"]
      max-commits: 1
```

This is useful for command line tools that will generate a chain of PRs with a single commit each.

**Comment by derekjobst** [comment]
Hey @atrocities , I've looked into implementing this feature a bit and wanted to check on a few things:

**1. Filter Types**
 If we re-use the existing filters used in the `trigger` block, logic for branch/label/comment filtering is included for free. This includes the following options:
```yaml
    labels: ["merge when ready"]
    comment_substrings: ["==MERGE_WHEN_READY=="]
    comments: ["Please merge this pull request!"]
    pr_body_substrings: ["==MERGE_WHEN_READY=="]
    branches: ["develop"]
    branch_patterns: ["feature/.*"]
```
I see you mentioned a `max-commits` filter. Would this also be necessary for your use case? Are there additional filters that would be required as well or instead? 

**2. Filter grouping**
Bulldozer merge triggering works if ANY filter matches, which I'm not sure would be appropriate in the case for choosing merge methods. For instance, the example use-case in the original issue above appears to require label `auto-push` AND label `generated` AND maximum 1 commits. Is that correct? 

Would simply requiring that ALL filters fully match be acceptable to your use case? I believe we could add flexibility by allowing any number of configurations for the same merge method.
