### ISSUE TITLE
Sporadic 403 "You have exceeded a secondary rate limit” errors

### ISSUE THREAD

**Issue by daiglebg** [palantir/bulldozer#276]
Our org currently has Bulldozer configured for 30 repos and 300+ open pull requests. We are seeing sporadic “403 You have exceeded a secondary rate limit” errors in our Bulldozer logs. Is it possible that Bulldozer is running too many concurrent api requests and github is throwing the 403 error? An example of the complete error is:

```
{
  "level": "error",
  "rid": "c7it9upsbsbhkcad330g",
  "github_event_type": "push",
  "github_delivery_id": "26036a76-77d6-11ec-9293-e49c7563bcc0",
  "github_installation_id": 6133582,
  "github_repository_owner": "OUR_ORG",
  "github_repository_name": "our_repo",
  "github_pr_num": 2424,
  "error": "unable to determine update status: failed to determine if pull request is ignored: failed to list pull request comments: GET https://api.github.com/repos/OUR_ORG/our_repo/pulls/2424/comments?per_page=100: 403 You have exceeded a secondary rate limit. Please wait a few minutes before you try again. []\ngithub.com/palantir/bulldozer/pull.(*GithubContext).Comments\n\t/go/src/github.com/palantir/bulldozer/pull/github_context.go:101\ngithub.com/palantir/bulldozer/bulldozer.(*Signals).Matches\n\t/go/src/github.com/palantir/bulldozer/bulldozer/signals.go:72\ngithub.com/palantir/bulldozer/bulldozer.IsPRIgnored\n\t/go/src/github.com/palantir/bulldozer/bulldozer/evaluate.go:30\ngithub.com/palantir/bulldozer/bulldozer.ShouldUpdatePR\n\t/go/src/github.com/palantir/bulldozer/bulldozer/update.go:35\ngithub.com/palantir/bulldozer/server/handler.(*Base).UpdatePullRequest\n\t/go/src/github.com/palantir/bulldozer/server/handler/base.go:91\ngithub.com/palantir/bulldozer/server/handler.(*Push).Handle\n\t/go/src/github.com/palantir/bulldozer/server/handler/push.go:80\ngithub.com/palantir/go-githubapp/githubapp.Dispatch.Execute\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/scheduler.go:56\ngithub.com/palantir/go-githubapp/githubapp.(*scheduler).safeExecute\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/scheduler.go:183\ngithub.com/palantir/go-githubapp/githubapp.QueueAsyncScheduler.func1\n\t/go/src/github.com/palantir/bulldozer/vendor/github.com/palantir/go-githubapp/githubapp/scheduler.go:257\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357",
  "time": "2022-01-17T20:44:20.087614922Z",
  "message": "Error updating pull request"
}
```

**Comment by bluekeyes** [comment]
Based on the error you shared, I'm guessing you have automatic branch updates enabled for this repository? That feature can definitely be expensive when a repository has many open pull requests that need to be updated. Each time a PR merges, Bulldozer needs to evaluate all open PRs to see if they need updates and the required API calls can add up. While it may not fit with your workflow, you can reduce requests by making updates opt-in (via the `trigger` configuration) rather than opt-out (via the `ignore` configuration.)

Otherwise, to further diagnose this, I think we'll want to look at the GitHub request logs. If you have debug logging enabled in Bulldozer, you can look at all messages with the `github_request` message. This should show when bursts of requests happen and which API endpoints are requested.

The request logs will also show the cache status of requests. Bulldozer maintains an in-memory cache for GitHub responses that is 50MB by default. One thing you could try is increasing the size of this cache and then checking request logs to see if cache hits have increased:

```yaml
cache:
  max_size: "100MB"
```

Cache metrics can also be exported to Datadog, but unfortunately, we don't support any other metric exporters yet.

**Comment by daiglebg** [comment]
Thank you for the reply. The information you supplied is very helpful. Our current bulldozer configuration is:

```
  default_repository_config:
    merge:
      trigger:
        labels: ["auto merge"]
        comment_substrings: ["==MERGE_WHEN_READY=="]
      ignore:
        labels: ["no auto merge"]
        comment_substrings: ["==DO_NOT_MERGE=="]
      method: squash
      options:
        squash:
          body: pull_request_body
          message_delimiter: <!-- COMMIT MESSAGE MARKER - DO NOT DELETE THIS -->
      delete_after_merge: true
    update:
      trigger:
        labels: ["auto update", "auto merge"]
      ignore:
        labels: ["no auto update"]

```
Currently in our 30 repos, we have 57 pull requests with the “auto update” label and 11 with the “auto merge” label applied. Many Bulldozer operations run successfully however, they start failing with the “403 You have exceeded a secondary rate limit. Please wait a few minutes before you try again” error, which I think indicates Bulldozer may be doing too many api requests, too quickly and the secondary rate limit kicks in. Could 68 PRs being processed by Bulldozer cause this? Is there a way to slow down some of the Bulldozer operations, e.g some delay variable setting etc?

We do have debug configured and I have access to the Bulldozer logs with a history of calls. I am attaching a compressed log, with our org and repo names replaced, but it has all other data. Please let me know if you need any more information.

In the attached log, you'll see that "OUR_REPO_7" seems to have more issues. That is our biggest repo and has the most PRs and therefore the most Bulldozer operations.

[bulldozer.log.gz](https://github.com/palantir/bulldozer/files/7906366/bulldozer.log.gz)
