### ISSUE TITLE
Bot fails to interpret .bulldozer.yml

### ISSUE THREAD

**Issue by dB2510** [palantir/bulldozer#304]
I have deployed bulldozer bot to our kubernetes cluster and here is my .bulldozer.yml that is present in our repo:
```
version: 1

merge:
  trigger:
    labels: ["merge when ready"]
    comment_substrings: ["==MERGE_WHEN_READY=="]
    branches: ["main"]
  ignore:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  options:
    squash:
      title: "github_default_title"
      body: pull_request_body
  delete_after_merge: true
  allow_merge_with_no_checks: false

update:
  trigger:
    labels: ["wip", "update me"]
```
From k8s logs, it seems that it identifies that .bulldozer.yml is present but fails to react accordingly. As soon as a PR is opened it merges it without any label or comment.

Any ideas what could be causing this?
