### ISSUE TITLE
Options can't be configured as ENV var

### ISSUE THREAD

**Issue by DepickereSven** [palantir/bulldozer#358]
I noticed some properties of the options on bulldozer don't have the capability to be configured as ENV var, on the docker image.
 
The following properties:
```yaml
# Options for application behavior
options:
  # The path within repositories to find the bulldozer.yml config file
  configuration_path: .bulldozer.yml

  # The name of the application. This will affect the User-Agent header
  # when making requests to Github.
  app_name: bulldozer

  # To reduce pressure on CI systems and Github, the update feature can be
  # disabled at the server level by specifying the following server option:
  disable_update_feature: true
```

I would propose that we use the same ENV name as you made possible for [Policy-bot](https://github.com/palantir/policy-bot/blob/develop/config/policy-bot.example.yml), so the options tab would have the prefix `BULLDOZER_OPTIONS_`

So to configure the following vars:
| YAML name   | ENV name   |
|:-:|:-:|
| options.configuration_path  | BULLDOZER_OPTIONS_CONFIGURATION_PATH    |
| options,app_name   | BULLDOZER_OPTIONS_APP_NAME    |
| options,push_restriction_user_token| BULLDOZER_OPTIONS_PUSH_RESTRICTION_USER_TOKEN  |
| options,shared_repository| BULLDOZER_OPTIONS_SHARED_REPOSITORY  |
| options,shared_configuration_path| BULLDOZER_OPTIONS_SHARED_CONFIGURATION_PATH  |
| options,disable_update_feature | BULLDOZER_OPTIONS_DISABLE_UPDATE_FEATURE  |

I would propose this change is a new PR.
