### ISSUE TITLE
Bulldozer is not auto merging my PRs

### ISSUE THREAD

**Issue by llopes-webera** [palantir/bulldozer#378]
Good afternoon, team. Thanks for your help in advance.
I'm figuring out an issue with Bulldozer that stopped to auto-merge my organization PRs around three weeks ago. I noted is kind of some changes by Engineers in the Helm Chart, like:

- Ingress
```
FROM: apiVersion: extensions/v1beta1
TO: apiVersion: networking.k8s.io/v1
---
FROM: - path: {{ $ingressPath }}
TO: - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
```

- Deployment
```
FROM: apiVersion: apps/v1beta2
TO: apiVersion: apps/v1
```

Also, the specification looks like some old one. Instead of `Trigger` and `Ignore`, there are using `Whitelist` and `Blacklist`. Is it some older version, please?
```
version: 1
merge:
  whitelist:
    labels:
    - ready for merge
    - merge
  blacklist:
    labels:
    - do not merge
    - wip
    - testing
  method: squash
  options:
    squash:
      body: pull_request_body
  delete_after_merge: true
update:
  whitelist:
    labels:
    - wip
    - update
    - ready for merge
    - merge
    - ready for review
```

My apologies for any dumb question, but I'm not much familiar with `Bulldozer`. Thank you very much for your support.
