### ISSUE TITLE
Bulldozer causing Github Action workflows set to run on merge to be skipped

### ISSUE THREAD

**Issue by reedog117** [palantir/bulldozer#524]
I have a GitHub Action workflow that's set to run whenever a PR is merged. It was working fine until I enabled bulldozer -- now the workflow jobs are being skipped.

The condition I'm using is below:

```yaml
jobs:
  create_release_after_merge:
    runs-on: ubuntu-latest
    # detect when PR is merged and the PR is for a merge to main
    if: (github.event.pull_request.merged == 'true' && github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch' )
```

Are bulldozer merges different from manual merges and this is causing my workflow to be skipped?
