### ISSUE TITLE
Control merge method through PR comment

### ISSUE THREAD

**Issue by kbakk** [palantir/bulldozer#567]
Hi! Thanks for sharing and maintaining this project! 🙌 

Sometimes we want to use different merge methods, based on the commits to a branch. It would be nice if we could control it per branch - e.g. by commenting on a PR with "bulldozer squash", which would have bulldozer do a squash merge.

```
merge:
  merge_method:
    - method: squash
      trigger:
        pr_comment: "bulldozer squash"
    - method: rebase
      trigger:
        pr_comment: "bulldozer rebase"
```

Would this behavior be desired? It could of course be completely disabled by not configuring it.

**Comment by bluekeyes** [comment]
It's not obvious from our docs, but I think this actually works today. I created a test project with the following configuration and it worked as you described. Bulldozer triggered when I left a comment (or added a label) and it used the appropriate merge method for that trigger to merge the PR:

```yaml
version: 1
merge:
  merge_method:
    - method: merge
      trigger:
        comments: ["bulldozer merge"]
    - method: merge
      trigger:
        labels: ["bulldozer: merge"]
    - method: squash
      trigger:
        comments: ["bulldozer squash"]
    - method: squash
      trigger:
        labels: ["bulldozer: squash"]
```

Please try it out and let me know if this is what you were looking for. Note that unlike the "standard" `trigger` block, when used in `merge_method`, _all_ of the triggers much match to select a method. That's why I had to duplicate the definitions for labels and comments, instead of combining them in to a single rule.
