### ISSUE TITLE
OR or AND option for required status

### ISSUE THREAD

**Issue by satizzzzz** [palantir/bulldozer#598]
Is there any OR or AND option available for required status. 

I've been working on different branches. Bulldozer bot should detect the required status according to the branches.

```
version: 1
merge:
  trigger:
    labels:
      - "automerge"
    branches: ["develop_backend", "develop_frontend"]
  method: squash
  options:
    squash:
      title: pull_request_title
      body: pull_request_body
  
  # Ensure all checks pass before merging
  required_statuses:
 #   - "Cycode: Secrets"
    - "ci/tekton"
    # - "policy-bot: develop_backend"
    - "policy-bot: develop_frontend"
  delete_after_merge: true
  allow_merge_with_no_checks: false
```

Above is my code, currently i have commented the required status  - "policy-bot: develop_frontend" for develop_backend branch anb vice versa.

Thanks in advance
