### ISSUE TITLE
Different Merge Options For Different Target Branches

### ISSUE THREAD

**Issue by eli-jordan** [palantir/bulldozer#89]
In our development model we are moving to using to shared branches `develop` and `master`. We would like to use different merge options for these targets. In our case, `squash` for merges into `develop` and `merge` for merges into master.

Something like this would be great.

```yaml
method: rebase
branch_merge_method: 
   develop: squash
   master: merge
```

Where the `method` attribute is used if there is no branch specific method that matches the current PR, otherwise the branch specific method is used.

This should be pretty simple to implement, so I'm happy to create a PR if you think this makes sense.
